---
galaxy_info:
  role_name: apt_signed_repo
  namespace: weisssrv
  author: Eric Weiss
  description: Shared pipeline to add a fingerprint-verified signed APT repository
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - trixie

dependencies: []
