---
platforms:
  - name: alloy-host-test
    image: ${MOLECULE_TEST_IMAGE:-registry.git.ericsweiss.com/eric/weisssrv-lib/molecule-test:latest}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
    stop_signal: SIGRTMIN+3
    tty: true
    tmpfs:
      - /run
      - /tmp
provisioner:
  inventory:
    group_vars:
      all:
        alloy_host_version: "1.17.1-1"
        alloy_host_loki_url: http://127.0.0.1:31100/loki/api/v1/push
