---
platforms:
  - name: zfs-exporter-test
    image: ${MOLECULE_TEST_IMAGE:-registry.git.ericsweiss.com/eric/weisssrv-lib/molecule-test:latest}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
    stop_signal: SIGRTMIN+3
    tty: true
    tmpfs:
      - /run
      - /tmp
provisioner:
  inventory:
    group_vars:
      all:
        zfs_exporter_version: 2.3.12
        zfs_exporter_port: 9134
