"""scripts/check-flux-version-pin.py holds CI, the ConfigMap and gotk to one version."""
from __future__ import annotations

import pytest

from script_loader import load_script

gate = load_script("check-flux-version-pin.py")

GOTK_HEADER = """# This manifest was generated by flux. DO NOT EDIT.
# Flux Version: v%s
# Components: %s
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
"""


def _repo(tmp_path, ci="2.7.4", configmap="2.7.4", gotk="2.7.4", components=None):
    (tmp_path / ".gitlab-ci.yml").write_text(
        'variables:\n  FLUX_VERSION: "%s"\n' % ci, encoding="utf-8"
    )
    cm = tmp_path / "kubernetes/infrastructure/sources/versions-configmap.yaml"
    cm.parent.mkdir(parents=True, exist_ok=True)
    cm.write_text("data:\n  flux_version: %s\n" % configmap, encoding="utf-8")
    if gotk is not None:
        manifest = tmp_path / "kubernetes/clusters/prod/flux-system/gotk-components.yaml"
        manifest.parent.mkdir(parents=True, exist_ok=True)
        manifest.write_text(
            GOTK_HEADER % (gotk, components or gate.DEFAULT_COMPONENTS), encoding="utf-8"
        )
    return tmp_path


def test_agreement_passes(tmp_path):
    code, report = gate.check(_repo(tmp_path))
    assert code == 0
    assert "Flux pinned at 2.7.4" in "\n".join(report)


def test_the_configmap_disagreeing_with_ci_fails(tmp_path):
    """Mutation case: the comparison, not the corpus."""
    code, report = gate.check(_repo(tmp_path, configmap="2.6.0"))
    assert code == 1
    assert "disagree" in "\n".join(report)


def test_gotk_disagreeing_with_ci_fails(tmp_path):
    code, report = gate.check(_repo(tmp_path, gotk="2.6.0"))
    assert code == 1
    assert "gotk-components.yaml" in "\n".join(report)


def test_a_runbook_is_named_in_the_re_export_line(tmp_path):
    """The doc that owns the upgrade is consumer site data, so it is an input."""
    code, report = gate.check(_repo(tmp_path, gotk="2.6.0"),
                              runbook="docs/flux-operations.md")
    assert code == 1
    assert "(see docs/flux-operations.md)" in "\n".join(report)


def test_without_a_runbook_the_line_names_no_doc(tmp_path):
    code, report = gate.check(_repo(tmp_path, gotk="2.6.0"))
    assert code == 1
    assert "(see " not in "\n".join(report)


def test_a_changed_component_set_fails(tmp_path):
    """A distribution change is not a version bump: it needs --components."""
    code, report = gate.check(_repo(tmp_path, components="source-controller"))
    assert code == 1
    assert "not %s" % gate.DEFAULT_COMPONENTS in "\n".join(report)


def test_a_declared_extra_component_set_passes(tmp_path):
    extra = gate.DEFAULT_COMPONENTS + ",image-reflector-controller"
    code, _ = gate.check(_repo(tmp_path, components=extra), components=extra)
    assert code == 0


def test_a_gotk_without_the_version_header_fails(tmp_path):
    repo = _repo(tmp_path)
    manifest = repo / "kubernetes/clusters/prod/flux-system/gotk-components.yaml"
    manifest.write_text(
        "# Components: %s\n" % gate.DEFAULT_COMPONENTS, encoding="utf-8"
    )
    code, report = gate.check(repo)
    assert code == 1
    assert "no '# Flux Version:' header" in "\n".join(report)


def test_a_pre_bootstrap_repo_still_compares_ci_and_the_configmap(tmp_path):
    code, report = gate.check(_repo(tmp_path, gotk=None))
    assert code == 0
    assert "checked the pin against the ConfigMap only" in "\n".join(report)
    code, _ = gate.check(_repo(tmp_path, configmap="2.6.0", gotk=None))
    assert code == 1


@pytest.mark.parametrize("missing", [".gitlab-ci.yml", "kubernetes"])
def test_an_unreadable_subject_is_an_operator_error(tmp_path, missing):
    """Exit 2, never a green pass: the gate inspected nothing."""
    repo = _repo(tmp_path)
    target = repo / missing
    if target.is_dir():
        for path in sorted(target.rglob("*"), reverse=True):
            path.unlink() if path.is_file() else path.rmdir()
        target.rmdir()
    else:
        target.unlink()
    code, report = gate.check(repo)
    assert code == 2
    assert "inspected nothing" in "\n".join(report)


def test_an_absent_flux_version_pin_is_an_operator_error(tmp_path):
    repo = _repo(tmp_path)
    (repo / ".gitlab-ci.yml").write_text("variables:\n  OTHER: 1\n", encoding="utf-8")
    code, report = gate.check(repo)
    assert code == 2
    assert "no FLUX_VERSION pin" in "\n".join(report)


def test_an_absent_configmap_key_is_an_operator_error(tmp_path):
    repo = _repo(tmp_path)
    (repo / "kubernetes/infrastructure/sources/versions-configmap.yaml").write_text(
        "data:\n  k3s_version: v1.36.4\n", encoding="utf-8"
    )
    code, report = gate.check(repo)
    assert code == 2
    assert "no flux_version key" in "\n".join(report)


def test_the_shell_and_yaml_pin_spellings_both_parse(tmp_path):
    """The pin is a shell assignment in a block scalar in most pipelines, and a
    YAML `variables:` entry in others."""
    repo = _repo(tmp_path)
    (repo / ".gitlab-ci.yml").write_text(
        'cluster-verify:\n  script:\n    - |\n      FLUX_VERSION="2.7.4"\n',
        encoding="utf-8",
    )
    assert gate.check(repo)[0] == 0


def test_a_declared_set_the_manifest_does_not_match_still_fails(tmp_path):
    """--components is the expectation, not an escape hatch."""
    repo = _repo(tmp_path, components=gate.DEFAULT_COMPONENTS)
    code, _ = gate.check(repo, components=gate.DEFAULT_COMPONENTS + ",image-automation-controller")
    assert code == 1


def test_main_returns_the_check_code(tmp_path, capsys):
    code = gate.main(["--repo-root", str(_repo(tmp_path, configmap="2.6.0"))])
    capsys.readouterr()
    assert code == 1
