---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "Reload and restart tailscaled"

- name: Restart tailscaled
  ansible.builtin.service:
    name: tailscaled
    state: restarted
  listen: "Reload and restart tailscaled"
