---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Read /etc/resolv.conf
      ansible.builtin.slurp:
        src: /etc/resolv.conf
      register: resolv_conf_content

    - name: Verify resolv.conf contains the configured nameservers + search domain
      ansible.builtin.assert:
        that:
          - "'nameserver 192.168.0.150' in (resolv_conf_content.content | b64decode)"
          - "'nameserver 192.168.0.160' in (resolv_conf_content.content | b64decode)"
          - "'search example.test' in (resolv_conf_content.content | b64decode)"
          - "'domain example.test' in (resolv_conf_content.content | b64decode)"
        fail_msg: "resolv.conf is missing expected nameservers or search domain"
        success_msg: "resolv.conf has correct nameservers and search domain"

    - name: Check file mode
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: resolv_conf_stat
      failed_when: resolv_conf_stat.stat.mode != "0644"
