---
galaxy_info:
  role_name: postfix_null_client
  namespace: weisssrv
  author: Eric Weiss
  description: Postfix null client (satellite system) forwarding to SMTP relay
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - trixie

dependencies: []
