---
galaxy_info:
  role_name: tailscale
  namespace: weisssrv
  author: Eric Weiss
  description: Tailscale VPN with subnet routing capabilities
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - trixie

dependencies: []
