---
- name: Restart sshd
  ansible.builtin.service:
    name: "{{ base_ssh_service_name | default('ssh') }}"
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  when: base_fail2ban_enabled | default(true)
