#!/usr/bin/env python3
"""Generate a Flux `cluster-versions` ConfigMap from an Ansible vars file.

Flattens every `*_version` key (and each --nested-key mapping) into the
postBuild substitution grammar. Idempotent. Contract: docs/SCRIPTS.md.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required: pip install pyyaml (or brew install python && pip3 install pyyaml)", file=sys.stderr)
    raise SystemExit(2) from None

VERSION_SUFFIX = "_version"
DEFAULT_NESTED_KEYS = ("helm_chart_versions",)
DEFAULT_NAME = "cluster-versions"
DEFAULT_NAMESPACE = "flux-system"
# Flux postBuild variable names: Go envsubst identifier rules (isLetter|isDigit|_).
FLUX_VAR_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _scalar_str(key: str, value: object) -> str:
    """Coerce a YAML scalar to the str form that Flux will substitute.

    Rejects bool and float, whose str() forms ship silently as a wrong image
    tag or chart version, and rejects anything non-scalar.
    """
    if isinstance(value, bool):
        raise ValueError(
            f"key {key!r} has bool value {value!r} — quote the value in the vars "
            "file (YAML's unquoted 'true'/'yes' parse to bool)"
        )
    if isinstance(value, float):
        raise ValueError(
            f"key {key!r} has float value {value!r} — quote the value in the vars "
            "file (an unquoted version like 1.20 parses to a float and loses precision)"
        )
    if not isinstance(value, (str, int)):
        raise ValueError(
            f"key {key!r} has non-scalar value (type {type(value).__name__}) — "
            "only quoted strings and ints are supported"
        )
    return str(value)


def flatten(data: dict, nested_keys: tuple[str, ...] = DEFAULT_NESTED_KEYS) -> dict[str, str]:
    """Flatten the version keys of a vars file into ConfigMap data.

    An empty value is a vars-file sentinel meaning "take the distro build", so
    the key is dropped and `${...}` stays visible instead of an empty tag.
    """
    out: dict[str, str] = {}
    for k, v in data.items():
        if k.endswith(VERSION_SUFFIX):
            if not FLUX_VAR_RE.match(k):
                raise ValueError(
                    f"top-level key {k!r} is not a valid Flux postBuild variable name"
                )
            # Coercion errors raise rather than skip: a silently dropped key is
            # an unresolved ${...} at reconcile time, and the "every key
            # dropped" guard below only catches the total case.
            value = _scalar_str(k, v)
            if value:
                out[k] = value
        elif k in nested_keys and isinstance(v, dict):
            for sub_k, sub_v in v.items():
                flat_key = f"{k}_{sub_k}"
                if not FLUX_VAR_RE.match(flat_key):
                    raise ValueError(
                        f"flattened key {flat_key!r} is not a valid Flux "
                        "postBuild variable name (needs [A-Za-z_][A-Za-z0-9_]*). "
                        f"Offending input: {k}.{sub_k}"
                    )
                value = _scalar_str(flat_key, sub_v)
                if value:
                    out[flat_key] = value
    return out


def header(vars_file: Path, regen_command: str) -> str:
    return (
        "---\n"
        f"# AUTO-GENERATED by generate-versions-configmap.py from\n"
        f"# {vars_file}. Do NOT edit by hand.\n"
        f"# Run `{regen_command}` to regenerate. CI fails if out of sync.\n"
    )


def render(
    flat: dict[str, str],
    vars_file: Path,
    *,
    name: str = DEFAULT_NAME,
    namespace: str = DEFAULT_NAMESPACE,
    regen_command: str = "generate-versions-configmap.py",
) -> str:
    """Return the full ConfigMap document text (header + YAML)."""
    cm = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": name, "namespace": namespace},
        "data": flat,
    }
    return header(vars_file, regen_command) + yaml.safe_dump(
        cm, default_flow_style=False, sort_keys=True
    )


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a Flux versions ConfigMap.")
    parser.add_argument("--vars-file", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--name", default=DEFAULT_NAME)
    parser.add_argument("--namespace", default=DEFAULT_NAMESPACE)
    parser.add_argument(
        "--nested-key", action="append", dest="nested_keys", default=None,
        help=f"repeatable; default: {DEFAULT_NESTED_KEYS[0]}",
    )
    parser.add_argument(
        "--regen-command", default="generate-versions-configmap.py",
        help="command named in the generated header (e.g. a task wrapper)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    nested_keys = tuple(args.nested_keys) if args.nested_keys else DEFAULT_NESTED_KEYS

    if not args.vars_file.exists():
        print(f"ERROR: {args.vars_file} not found", file=sys.stderr)
        return 1
    try:
        with args.vars_file.open() as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError as e:
        print(f"ERROR: failed to parse {args.vars_file}: {e}", file=sys.stderr)
        return 1
    if data is None:
        print(f"ERROR: {args.vars_file} is empty", file=sys.stderr)
        return 1
    if not isinstance(data, dict):
        print(
            f"ERROR: {args.vars_file} top-level is not a mapping "
            f"(got {type(data).__name__})",
            file=sys.stderr,
        )
        return 1

    try:
        flat = flatten(data, nested_keys)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    if not flat:
        print("ERROR: no version keys extracted; check the vars file structure", file=sys.stderr)
        return 1

    text = render(
        flat,
        args.vars_file,
        name=args.name,
        namespace=args.namespace,
        regen_command=args.regen_command,
    )
    try:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text)
    except OSError as e:
        print(f"ERROR: failed to write {args.output}: {e}", file=sys.stderr)
        return 1
    print(f"Wrote {len(flat)} keys to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
