---
galaxy_info:
  role_name: proxmox_firewall
  namespace: weisssrv
  author: Eric Weiss
  description: Proxmox VE firewall management (cluster, host, guest, IPSets, Security Groups)
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - trixie

dependencies: []
